services:
  supabase-db:
    image: supabase/postgres:15.8.1.100
    restart: always
    ports:
      - '54322:5432'
    volumes:
      - ./supabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
