services:
  supabase-db:
    image: supabase/postgres:15.8.1.100
    restart: always
    ports:
      - '54322:5432'
    volumes:
      - ./supabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  supabase-rest:
    image: postgrest/postgrest:v12.2.12
    restart: always
    depends_on:
      - supabase-db
    ports:
      - '3000:3000'
    environment:
      PGRST_DB_URI: ${DATABASE_URL}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
