services:
  postgres-db:
    image: postgres:16.9
    restart: always
    ports:
      - '54322:5432'
    volumes:
      - ./postgreSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.2.9-alpine
    restart: always
    ports:
      - '6379:6379'
